### ISSUE TITLE
define same multipe uri with different method

### ISSUE THREAD

**Issue by praswicaksono** [psecio/invoke#6]
for example I have this config

``` yml
/user/login:
  groups: [Admin]
  methods: [post]
/user/login:
  groups: [Guest]
  methods: [get]
```

It seem yml loader wont load same key twice, is there any solution?
