### ISSUE TITLE
Multiple groups per route

### ISSUE THREAD

**Issue by praswicaksono** [psecio/invoke#7]
for example I have this config

``` yml
/show/news:
  groups: [Guest, Member]
  methods: [post]
```

In those config user will need in `Guest` AND `Member`, is this library designed that way? I think it would be better if user can access those route when it in `Guest` or `Member` group.

What do you think?
